version: "3.10"
   
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: sh -c "chmod +x ./run.sh && ./run.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
